export const CLICK_PERCENTAGE = 'CLICK_PERCENTAGE';
export const CLICK_INVERT = 'CLICK_INVERT';
export const CLICK_NUMBER = 'CLICK_NUMBER';
export const CLICK_DECIMAL = 'CLICK_DECIMAL';
export const CLICK_OPERATOR = 'CLICK_OPERATOR';
export const CALCULATE = 'CALCULATE';
export const CLEAR = 'CLEAR';
